" Pathogen load
filetype off

call pathogen#infect()
call pathogen#helptags()

filetype plugin indent on

syntax on
set nocompatible
set number
set showmatch
set hlsearch
set cursorline
set foldmethod=marker
set incsearch
set autoindent
set autowrite
set expandtab
set softtabstop=4 
set tabstop=4 
set shiftwidth=4
set hidden
set nowrap
colorscheme torte
" automatically switch to directory where the file is located
set autochdir

" set default encoding
set encoding=utf-8
set fileencoding=utf-8

let mapleader=","       " leader is comma

" allows cursor change in tmux mode
if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" there exist modern ways for tracking your changes...
set nobackup
set noswapfile

" autocomplete to longest available
set wildmode=list:longest

" spell vis settings
hi clear SpellBad
hi SpellBad ctermfg=red term=underline cterm=underline guifg=red gui=underline
hi clear SpellCap
hi SpellCap term=underline cterm=underline
hi clear SpellRare
hi SpellRare term=underline cterm=underline
hi clear SpellLocal
hi SpellLocal term=underline cterm=underline

" assign filetypes if not automatically detected
autocmd BufRead,BufNewFile *.txt setfiletype text

" Open terminal via <F8> key
map <F8> :silent ! mate-terminal &<CR>

" <CTRL-Y> inserts whole word from line above instead of single char
inoremap <expr> <c-y> matchstr(getline(line('.')-1), '\%' . virtcol('.') . 'v\%(\k\+\\|.\)')
inoremap <expr> <c-e> matchstr(getline(line('.')+1), '\%' . virtcol('.') . 'v\%(\k\+\\|.\)')

" CtrlP activation
set runtimepath^=~/.vim/bundle/ctrlp.vim

" Ultisnips / snipmate author info
let g:snips_author = "Christoph Hermes"
let g:snips_email = "hermes@hausmilbe.net"
let g:snips_github = "https://github.com/chermes"
let g:ultisnips_python_style = "numpy"

"""""""""""""""""""""""""""""""""""
"  Python-dependent break points  "
"""""""""""""""""""""""""""""""""""
autocmd FileType python map <F5> aimport IPython; IPython.embed()<ESC>
autocmd FileType python imap <F5> import IPython; IPython.embed()
" can deal with threads
autocmd FileType python map <C-F5> afrom PyQt4.QtCore import pyqtRemoveInputHook; pyqtRemoveInputHook()<ESC>
autocmd FileType python imap <C-F5> from PyQt4.QtCore import pyqtRemoveInputHook; pyqtRemoveInputHook()
" close the debugging shell / script
autocmd FileType python map <S-F5> aimport sys; sys.exit()<ESC>
autocmd FileType python imap <S-F5> import sys; sys.exit()
" insert timestamp
autocmd FileType python nmap <F3> a<C-R>=strftime("%Y-%m-%d %a %I:%M %p")<CR><Esc>
autocmd FileType python imap <F3> <C-R>=strftime("%Y-%m-%d %a %I:%M %p")<CR>

" jedi-vim: disable the '.' expansion by default (can be triggered by <c-x o>
let g:jedi#popup_on_dot = 0
" ignore certain directories in the CtrlP plugin:
:let g:ctrlp_custom_ignore = 'node_modules\|__pycache__\|git'
